### ISSUE TITLE
Traducir la documentación y agregar contenido relacionado a los steps de los pipelines en cuanto a inspección continua y pruebas

### ISSUE THREAD

**Issue by jesanbrito** [isiiunab/run-deploy#47]
Traducción de la documentación, agregar contenido relacionado a los Steps de los pipelines.

**Comment by isiiunab** [comment]
Revisar la documentación, no pueden quedar los links expuestos 
`Implemente la imagen en [Cloud Run] (https://cloud.google.com/run/).`
Eliminar el espacio entre ] y (

**Comment by edna2709** [comment]
El readme original contiene los enlaces, entonces los quitamos cuando se haga la traducción? o como debería quedar el documento?
